%fatos
carta(4).
carta(5).
carta(6).
carta(7).
carta(q).
carta(j).
carta(k).
carta(a).
carta(2).
carta(3).
carta(7).
carta(a).
carta(7).
carta(4).


ouros(carta(4),1).
ouros(carta(5),2).
ouros(carta(6),3).
ouros(carta(7),4).
ouros(carta(q),5).
ouros(carta(j),6).
ouros(carta(k),7).
ouros(carta(a),8).
ouros(carta(2),9).
ouros(carta(3),10).

paus(carta(4),1).
paus(carta(5),2).
paus(carta(6),3).
paus(carta(7),4).
paus(carta(q),5).
paus(carta(j),6).
paus(carta(k),7).
paus(carta(a),8).
paus(carta(2),9).
paus(carta(3),10).

copas(carta(4),1).
copas(carta(5),2).
copas(carta(6),3).
copas(carta(7),4).
copas(carta(q),5).
copas(carta(j),6).
copas(carta(k),7).
copas(carta(a),8).
copas(carta(2),9).
copas(carta(3),10).

espadas(carta(4),1).
espadas(carta(5),2).
espadas(carta(6),3).
espadas(carta(7),4).
espadas(carta(q),5).
espadas(carta(j),6).
espadas(carta(k),7).
espadas(carta(a),8).
espadas(carta(2),9).
espadas(carta(3),10).

manilha(carta(7),11).
manilha(carta(a),12).
manilha(carta(7),13).
manilha(carta(4),14).


baralho(ouros(carta(4),1)).
baralho(ouros(carta(5),2)).
baralho(ouros(carta(6),3)).
baralho(ouros(carta(7),4)).
baralho(ouros(carta(q),5)).
baralho(ouros(carta(j),6)).
baralho(ouros(carta(k),7)).
baralho(ouros(carta(a),8)).
baralho(ouros(carta(2),9)).
baralho(ouros(carta(3),10)).
baralho(espadas(carta(4),1)).
baralho(espadas(carta(5),2)).
baralho(espadas(carta(6),3)).
baralho(espadas(carta(7),4)).
baralho(espadas(carta(q),5)).
baralho(espadas(carta(j),6)).
baralho(espadas(carta(k),7)).
baralho(espadas(carta(a),8)).
baralho(espadas(carta(2),9)).
baralho(espadas(carta(3),10)).
baralho(paus(carta(4),1)).
baralho(paus(carta(5),2)).
baralho(paus(carta(6),3)).
baralho(paus(carta(7),4)).
baralho(paus(carta(q),5)).
baralho(paus(carta(j),6)).
baralho(paus(carta(k),7)).
baralho(paus(carta(a),8)).
baralho(paus(carta(2),9)).
baralho(paus(carta(3),10)).
baralho(copas(carta(4),1)).
baralho(copas(carta(5),2)).
baralho(copas(carta(6),3)).
baralho(copas(carta(7),4)).
baralho(copas(carta(q),5)).
baralho(copas(carta(j),6)).
baralho(copas(carta(k),7)).
baralho(copas(carta(a),8)).
baralho(copas(carta(2),9)).
baralho(copas(carta(3),10)).
baralho(manilha(carta(7),11)).
baralho(manilha(carta(a),12)).
baralho(manilha(carta(7),13)).
baralho(manilha(carta(4),14)).
